/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfrastructureVmsRouteImport } from './routes/infrastructure.vms'
import { Route as InfrastructureStorageRouteImport } from './routes/infrastructure.storage'
import { Route as InfrastructureServersRouteImport } from './routes/infrastructure.servers'
import { Route as InfrastructureNetworkRouteImport } from './routes/infrastructure.network'
import { Route as InfrastructureMapRouteImport } from './routes/infrastructure.map'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureVmsRoute = InfrastructureVmsRouteImport.update({
  id: '/infrastructure/vms',
  path: '/infrastructure/vms',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureStorageRoute = InfrastructureStorageRouteImport.update({
  id: '/infrastructure/storage',
  path: '/infrastructure/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureServersRoute = InfrastructureServersRouteImport.update({
  id: '/infrastructure/servers',
  path: '/infrastructure/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureNetworkRoute = InfrastructureNetworkRouteImport.update({
  id: '/infrastructure/network',
  path: '/infrastructure/network',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureMapRoute = InfrastructureMapRouteImport.update({
  id: '/infrastructure/map',
  path: '/infrastructure/map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/infrastructure/map': typeof InfrastructureMapRoute
  '/infrastructure/network': typeof InfrastructureNetworkRoute
  '/infrastructure/servers': typeof InfrastructureServersRoute
  '/infrastructure/storage': typeof InfrastructureStorageRoute
  '/infrastructure/vms': typeof InfrastructureVmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/infrastructure/map': typeof InfrastructureMapRoute
  '/infrastructure/network': typeof InfrastructureNetworkRoute
  '/infrastructure/servers': typeof InfrastructureServersRoute
  '/infrastructure/storage': typeof InfrastructureStorageRoute
  '/infrastructure/vms': typeof InfrastructureVmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/infrastructure/map': typeof InfrastructureMapRoute
  '/infrastructure/network': typeof InfrastructureNetworkRoute
  '/infrastructure/servers': typeof InfrastructureServersRoute
  '/infrastructure/storage': typeof InfrastructureStorageRoute
  '/infrastructure/vms': typeof InfrastructureVmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/help'
    | '/inventory'
    | '/login'
    | '/monitoring'
    | '/profile'
    | '/register'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/users'
    | '/infrastructure/map'
    | '/infrastructure/network'
    | '/infrastructure/servers'
    | '/infrastructure/storage'
    | '/infrastructure/vms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/help'
    | '/inventory'
    | '/login'
    | '/monitoring'
    | '/profile'
    | '/register'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/users'
    | '/infrastructure/map'
    | '/infrastructure/network'
    | '/infrastructure/servers'
    | '/infrastructure/storage'
    | '/infrastructure/vms'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/help'
    | '/inventory'
    | '/login'
    | '/monitoring'
    | '/profile'
    | '/register'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/users'
    | '/infrastructure/map'
    | '/infrastructure/network'
    | '/infrastructure/servers'
    | '/infrastructure/storage'
    | '/infrastructure/vms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  InfrastructureMapRoute: typeof InfrastructureMapRoute
  InfrastructureNetworkRoute: typeof InfrastructureNetworkRoute
  InfrastructureServersRoute: typeof InfrastructureServersRoute
  InfrastructureStorageRoute: typeof InfrastructureStorageRoute
  InfrastructureVmsRoute: typeof InfrastructureVmsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/vms': {
      id: '/infrastructure/vms'
      path: '/infrastructure/vms'
      fullPath: '/infrastructure/vms'
      preLoaderRoute: typeof InfrastructureVmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/storage': {
      id: '/infrastructure/storage'
      path: '/infrastructure/storage'
      fullPath: '/infrastructure/storage'
      preLoaderRoute: typeof InfrastructureStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/servers': {
      id: '/infrastructure/servers'
      path: '/infrastructure/servers'
      fullPath: '/infrastructure/servers'
      preLoaderRoute: typeof InfrastructureServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/network': {
      id: '/infrastructure/network'
      path: '/infrastructure/network'
      fullPath: '/infrastructure/network'
      preLoaderRoute: typeof InfrastructureNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/map': {
      id: '/infrastructure/map'
      path: '/infrastructure/map'
      fullPath: '/infrastructure/map'
      preLoaderRoute: typeof InfrastructureMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  InfrastructureMapRoute: InfrastructureMapRoute,
  InfrastructureNetworkRoute: InfrastructureNetworkRoute,
  InfrastructureServersRoute: InfrastructureServersRoute,
  InfrastructureStorageRoute: InfrastructureStorageRoute,
  InfrastructureVmsRoute: InfrastructureVmsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-router' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
